### ISSUE TITLE
New schemas are not created

### ISSUE THREAD

**Issue by diego-duarte** [vonbraunlabs/sql-ddl-generator#1]
The command to create a schema is executed only once, for the first script. After that, it is ignored, even if you specify a new schema name into the model file

Exemplo: if you provide two schema files as following:
```
{
    "name": "foo",
    "table": {
        "name": "bla"
    }
}
```

AND 

```
{
    "name": "bla",
    "table": {
        "name": "foo"
    }
}
```

it will generate:
```
CREATE SCHEMA `foo`;
CREATE TABLE `foo`.`bla`;
CREATE TABLE `bla`.`foo`;
```

**Comment by dmelo** [comment]
Fixed on some previous version.
